### ISSUE TITLE
Bug with path to dist folder when deployed to linux

### ISSUE THREAD

**Issue by maraf** [maraf/Money#126]
```
Application startup exception: System.ArgumentException: The directory name /home/maraf/dist/ is invalid.
Parameter name: path
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at System.IO.FileSystemWatcher..ctor(String path)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.CreateFileWatcher(String root)
   at Microsoft.AspNetCore.Builder.BlazorAppBuilderExtensions.UseBlazor(IApplicationBuilder applicationBuilder, BlazorOptions options)
   at Microsoft.AspNetCore.Builder.BlazorAppBuilderExtensions.UseBlazor[TProgram](IApplicationBuilder applicationBuilder)
   at Money.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in D:\Development\Maraf\Money\src\Money.UI.Backend\Startup.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.ArgumentException: The directory name /home/maraf/dist/ is invalid.
Parameter name: path
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at System.IO.FileSystemWatcher..ctor(String path)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.CreateFileWatcher(String root)
   at Microsoft.AspNetCore.Builder.BlazorAppBuilderExtensions.UseBlazor(IApplicationBuilder applicationBuilder, BlazorOptions options)
   at Microsoft.AspNetCore.Builder.BlazorAppBuilderExtensions.UseBlazor[TProgram](IApplicationBuilder applicationBuilder)
   at Money.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in D:\Development\Maraf\Money\src\Money.UI.Backend\Startup.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Unhandled Exception: System.ArgumentException: The directory name /home/maraf/dist/ is invalid.
Parameter name: path
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at System.IO.FileSystemWatcher..ctor(String path)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.CreateFileWatcher(String root)
   at Microsoft.AspNetCore.Builder.BlazorAppBuilderExtensions.UseBlazor(IApplicationBuilder applicationBuilder, BlazorOptions options)
   at Microsoft.AspNetCore.Builder.BlazorAppBuilderExtensions.UseBlazor[TProgram](IApplicationBuilder applicationBuilder)
   at Money.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in D:\Development\Maraf\Money\src\Money.UI.Backend\Startup.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Money.Program.BuildWebHost(String[] args) in D:\Development\Maraf\Money\src\Money.UI.Backend\Program.cs:line 22
   at Money.Program.Main(String[] args) in D:\Development\Maraf\Money\src\Money.UI.Backend\Program.cs:line 18
Aborted
```

**Comment by maraf** [comment]
Relates to #aspnet/Blazor/376.

**Comment by maraf** [comment]
Works like a charm with custom build of `Microsoft.AspNetCore.Blazor.Server` from aspnet/Blazor#473.
