### ISSUE TITLE
It may happen that main menu is missing user info

### ISSUE THREAD

**Issue by maraf** [maraf/Money#467]
- No login or user info is present
- Happens on mobile and desktop as well
- I filled in login info and then accidentally clicked on demo login. I was previously signed-in on this device, but probably the token has expired

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Arg_UnauthorizedAccessException
System.UnauthorizedAccessException: Arg_UnauthorizedAccessException
   at Money.Services.ApiClient.EnsureSuccessResponseAsync(HttpResponseMessage responseMessage)
   at Money.Services.ApiClient.<ReadJsonSuccessResponseAsync>d__13`1[[Money.Api.Models.Response, Money.Api.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Money.Services.ApiClient.QueryAsync(Type type, String payload)
   at Neptuo.Queries.HttpQueryDispatcher.ExecuteRawAsync(Object query)
   at Money.MenuItemService.Neptuo.Queries.HttpQueryDispatcher.IMiddleware.ExecuteAsync(Object query, HttpQueryDispatcher dispatcher, Next next)
   at Money.Services.UserPropertyQueryHandler.ExecuteAsync(Object query, HttpQueryDispatcher dispatcher, Next next)
   at Money.Services.ExpenseTemplateMiddleware.ExecuteAsync(Object query, HttpQueryDispatcher dispatcher, Next next)
   at Money.Services.UserPropertyMiddleware.ExecuteAsync(Object query, HttpQueryDispatcher dispatcher, Next next)
   at Money.Services.UserMiddleware.LoadProfileAsync(GetProfile query, Next next)
   at Money.Services.UserMiddleware.ExecuteAsync(Object query, HttpQueryDispatcher dispatcher, Next next)
   at Money.Services.CurrencyMiddleware.ExecuteAsync(Object query, HttpQueryDispatcher dispatcher, Next next)
   at Money.Services.CategoryMiddleware.ExecuteAsync(Object query, HttpQueryDispatcher dispatcher, Next next)
   at Neptuo.Queries.HttpQueryDispatcher.<QueryAsync>d__6`1[[Money.Models.ProfileModel, Money.Accounts.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Money.Services.ApiTokenValidator.ValidateAsync(String token)
   at Money.Services.ApiAuthenticationStateProvider.ValidateTokenAsync(String token)
   at Money.Services.ApiAuthenticationStateProvider.ChangeTokenAsync(String value, Boolean isValidationRequired, Boolean isNoficationEnabled)
   at Money.Services.ApiAuthenticationStateProvider.LoadAndApplyTokenAsync()
   at Money.Services.ApiAuthenticationStateProvider.GetTokenAsync()
   at Money.Services.ApiAuthenticationStateProvider.GetAuthenticationStateAsync()
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
```

**Comment by maraf** [comment]
Tested
- Create a short lived token and wait for it's expiration => works fine
- Modify the serialized token to make it invalid => works fine
